build:
  stage: build
  image: docker.synotio.se/synotio/httpd_php70_gulp:latest
  only:
    - triggers
  except:
    - /^build-.*$/
  script:
    - npm install --only=prod
    - cd client
    - npm install
    - npm run build
    - cd ..
    - /bin/bash /docker/githelper2.sh
