build:
  stage: build
  image: docker.synotio.se/synotio/httpd_php70_gulp:latest
  except:
    - /^build-.*$/
  script:
    - npm install
    - cd client
    - npm install
    - npm run build
    - /bin/bash /docker/githelper2.sh
