build:
  stage: build
  image: docker.synotio.se/synotio/httpd_php70_gulp:latest
  only:
    - triggers
  except:
    - /^build-.*$/
  script:
    - yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 ipa-gothic-fonts xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc -y
    - npm install --only=prod
    - cd client
    - npm install
    - npm run build
    - cd ..
    - /bin/bash /docker/githelper2.sh
