name: Cyrpess Tests

on: [push, repository_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: cd client && npm build && npm serve -l 5000 -s build
          wait-on: 'http://localhost:5000'